### ISSUE TITLE
Errori di compilazione

### ISSUE THREAD

**Issue by AndreaRibuoli** [cdomizi/EserciziC#1]
Ciao Cesare,

  nel codice sorgente ci sono degli errori:

1) l'array con le stringhe degli argomenti passati dall'utente sulla riga comandi si chiama **argv**, tu hai usato erroneamente *argc* che ne riporta il numero:

```
primo.c:7:58: error: subscripted value is not an array, pointer, or vector
  if (argc>1) printf("Primo argomento utente: %s\n", argc[1]);
                                                     ~~~~^~
```
 2) il C prevede che ogni istruzione sia terminata con il punto e virgola `;`

```
primo.c:14:16: error: expected ';' after return statement
      return -1
               ^
               ;
```

**Comment by cdomizi** [comment]
Grazie per le correzioni. Ho scritto il codice come avrei recitato una poesia in una lingua sconosciuta; presto errori come questi non mi sfuggiranno più.

Risolto con la commit `fa407f2ef7643960767872bc288bc219527b6d0b`.
